{% set name = "datacache" %}
{% set version = "1.5.0" %}
{% set sha256 = "5e80a6263d14340bbf02586ffc942baa5ce37af31f456095ef30537e97c353e9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
    - setuptools
  run:
    - python
    - pandas >=0.15.2
    - appdirs >=1.4.0
    - progressbar33 >=2.4
    - biopython >=1.65
    - requests >=2.5.1
    - typechecks >=0.0.2
    - mock

test:
  imports:
    - datacache

about:
  home: https://github.com/openvax/datacache
  license: Apache-2.0
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Helpers for transparently downloading datasets'

extra:
  recipe-maintainers:
    - npavlovikj
